name:                brick-test
version:             0.1.0.0
github:              "mikiyaf/brick-test"
license:             BSD3
author:              "Mikiya Michishita"
maintainer:          "example@example.com"
copyright:           "2019 Mikiya Michishita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mikiyaf/brick-test#readme>

dependencies:
- base >= 4.7 && < 5
- brick

library:
  source-dirs: src

executables:
  brick-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brick-test

tests:
  brick-test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brick-test
